### PR TITLE
Implement voting for questions, answers, and responses

### PR DESCRIPTION
**Pull request by philsof**
This pull request implements voting across questions, answers, and responses. The following is covered:

-The asker of a question cannot vote on their own question
-The answerer of an answer cannot vote on their own answer
-The responder of a response cannot vote on their own response
-Once the current user has voted once on any given question, answer, or response, they cannot vote again on that object (the voting buttons disappear)
-There is now a vote_count attribute for all questions, answers, and responses. This vote_count attribute automatically updates on the parent object whenever a new vote record is saved to the database (via an after_save callback on the vote model that calls the respective method from the respective model). These vote counts are also visible next to each object, and increment properly immediately upon voting.

Let me know if I missed anything!

@kimchanyoung @jeder28 @saraho-shea

### CODE REVIEW

**Comment by philsof** [comment]
Anyone have any idea what the error message on the circleci test means for this pull request? @jeder28 @kimchanyoung @saraho-shea

**Comment by philsof** [comment]
I am working on eliminating the failing tests, will push changes soon.

**Comment by jeder28** [comment]
Yeah if you click on details for the failing tests it says theres an rspec error.
Did you check that rspec is passing tests?

**Comment by philsof** [comment]
it was that I hadn't upgraded ruby to 2.2.3 and committed the schema, since there were migration changes.  The branch passes the rspec tests now, because the server can run the migrations. @jeder28

**Pull request merged**
